"""
DRAGON SLAYER PART 2: Salvage Analysis

The full Z_3 x Z_3 action has fixed curves from pure g1, g2 elements.
But the DIAGONAL Z_3 subgroups (generated by g1*g2 and g1*g2^2) passed
the fixed-point test.

This script:
1. Rigorously confirms the diagonal Z_3 acts freely
2. Computes what chi the diagonal quotient gives
3. Numerically checks for fixed points by evaluating the polynomial
4. Searches for any other freely-acting subgroup
"""

import cytools as cy
import numpy as np
import sympy as sp
from itertools import combinations

PASS = "\033[92mPASS\033[0m"
FAIL = "\033[91mFAIL\033[0m"
WARN = "\033[93mWARN\033[0m"

def section(title):
    print(f"\n{'='*60}")
    print(f"  {title}")
    print(f"{'='*60}")

def compose_perm(p, q):
    return [p[q[i]] for i in range(len(p))]

def apply_perm_to_monomial(m, p):
    b = [0] * 6
    for i in range(6):
        b[p[i]] = m[i]
    return tuple(b)

def main():
    print("=" * 60)
    print("  DRAGON SLAYER PART 2: Salvage Analysis")
    print("=" * 60)
    
    # Setup
    polys = cy.fetch_polytopes(h11=2, lattice="N", limit=1)
    poly = polys[0]
    verts = poly.vertices()
    chi = poly.chi("N")
    h11_val = poly.h11("N")
    h21_val = poly.h21("N")
    
    print(f"Polytope: h11={h11_val}, h21={h21_val}, chi={chi}")
    
    # Generators
    g1 = [4, 1, 2, 3, 5, 0]  # (0 4 5)
    g2 = [0, 2, 3, 1, 4, 5]  # (1 2 3)
    identity = list(range(6))
    
    # Monomials
    dual_pts = poly.dual().points()
    monomials = []
    for m in dual_pts:
        powers = []
        for v in verts:
            powers.append(int(np.dot(m, v) + 1))
        monomials.append(tuple(powers))
    
    # =========================================================
    # TEST 1: DIAGONAL Z_3 SUBGROUPS
    # =========================================================
    section("1. Diagonal Z_3 Subgroups")
    
    # Subgroup 1: <g1*g2>
    h1 = compose_perm(g1, g2)  # g1*g2 as a permutation
    # Wait, need to be careful. compose_perm(p,q) = p[q[i]]
    # So compose_perm(g1, g2) means: first apply g2, then g1
    # Let me use a different convention for clarity
    
    def apply_g_then_h(g, h):
        """Return the permutation that first applies g, then h."""
        return [h[g[i]] for i in range(len(g))]
    
    # Diagonal 1: g1 * g2 (apply g1 then g2... or g2 then g1? Order matters for notation)
    # Since they commute, it doesn't matter!
    diag1_gen = compose_perm(g1, g2)  # g1 ∘ g2
    diag1_gen_sq = compose_perm(diag1_gen, diag1_gen)
    diag1_gen_cube = compose_perm(diag1_gen_sq, diag1_gen)
    
    print(f"Diagonal subgroup 1: <g1∘g2>")
    print(f"  g1∘g2 = {diag1_gen}")
    print(f"  (g1∘g2)² = {diag1_gen_sq}")
    print(f"  (g1∘g2)³ = {diag1_gen_cube}  (should be identity)")
    assert diag1_gen_cube == identity, "g1*g2 does not have order 3!"
    
    # Diagonal 2: g1 * g2^2
    g2_sq = compose_perm(g2, g2)
    diag2_gen = compose_perm(g1, g2_sq)
    diag2_gen_sq = compose_perm(diag2_gen, diag2_gen)
    diag2_gen_cube = compose_perm(diag2_gen_sq, diag2_gen)
    
    print(f"\nDiagonal subgroup 2: <g1∘g2²>")
    print(f"  g1∘g2² = {diag2_gen}")
    print(f"  (g1∘g2²)² = {diag2_gen_sq}")
    print(f"  (g1∘g2²)³ = {diag2_gen_cube}  (should be identity)")
    assert diag2_gen_cube == identity, "g1*g2^2 does not have order 3!"
    
    # =========================================================
    # TEST 2: FIXED POINT CHECK FOR DIAGONAL SUBGROUPS
    # =========================================================
    section("2. Fixed Point Check for Diagonal Z_3 Subgroups")
    
    # For each diagonal subgroup, check all non-identity elements
    for name, gen, gen_sq in [
        ("Diagonal 1 <g1∘g2>", diag1_gen, diag1_gen_sq),
        ("Diagonal 2 <g1∘g2²>", diag2_gen, diag2_gen_sq)
    ]:
        print(f"\n--- {name} ---")
        
        for elem_name, g in [("generator", gen), ("generator²", gen_sq)]:
            print(f"\n  Element: {elem_name} = {g}")
            
            # Find cycle structure
            visited = [False] * 6
            cycles = []
            for i in range(6):
                if not visited[i]:
                    cycle = []
                    j = i
                    while not visited[j]:
                        visited[j] = True
                        cycle.append(j)
                        j = g[j]
                    if len(cycle) > 1:
                        cycles.append(cycle)
            
            print(f"  Cycle structure: {cycles}")
            
            if len(cycles) != 2:
                print(f"  {WARN}: Expected 2 disjoint 3-cycles, got {len(cycles)}")
                continue
            
            # For combined elements with 2 disjoint 3-cycles:
            # The fixed locus is 0-dimensional (two omega-cases, 2 free coords - 2 C*)
            # The polynomial evaluates to a NUMBER on this locus.
            # If the number is generically nonzero, we're safe.
            
            # Compute the phase for each monomial
            surviving = []
            for m in monomials:
                phase = 0
                for c in cycles:
                    a_idx = c[0]
                    b_idx = g[a_idx]
                    c_idx = g[b_idx]
                    phase += m[b_idx] + 2 * m[c_idx]
                phase = phase % 3
                if phase == 0:
                    degs = tuple(sum(m[i] for i in c) for c in cycles)
                    surviving.append((m, degs))
            
            print(f"  Surviving monomials on fixed locus: {len(surviving)}")
            
            if len(surviving) == 0:
                print(f"  {FAIL}: Polynomial vanishes identically on Fix => fixed points on CY!")
            else:
                deg_pairs = set(d for _, d in surviving)
                print(f"  Degree pairs: {deg_pairs}")
                
                # The fixed locus is 0-dimensional, so the polynomial evaluates to a number.
                # Let's actually COMPUTE this number for random invariant coefficients.
                
                # Build the orbit-sum invariant polynomial
                # First, compute orbits under the FULL Z_3 x Z_3 (to get the most invariant poly)
                full_group = []
                curr = identity[:]
                for i in range(3):
                    temp = curr[:]
                    for j in range(3):
                        full_group.append(temp[:])
                        temp = compose_perm(g2, temp)
                    curr = compose_perm(g1, curr)
                
                orbits = []
                visited_m = set()
                for m in monomials:
                    if m not in visited_m:
                        orbit = set()
                        for grp in full_group:
                            orbit.add(apply_perm_to_monomial(m, grp))
                        orbits.append(orbit)
                        visited_m.update(orbit)
                
                # Now compute the polynomial on the fixed locus
                # For random coefficients c_k (one per orbit):
                np.random.seed(42)
                n_trials = 100
                n_nonzero = 0
                
                for trial in range(n_trials):
                    coeffs = np.random.randn(len(orbits)) + 1j * np.random.randn(len(orbits))
                    
                    # For each orbit, compute the orbit sum evaluated at the fixed point
                    # At the fixed point: 
                    #   For cycle c = [a,b,c]: x_b = omega*x_a, x_c = omega^2*x_a
                    #   Choose x_a = 1 for each cycle (fixing the torus)
                    omega = np.exp(2j * np.pi / 3)
                    
                    # Set up coordinates at the fixed point
                    x = np.ones(6, dtype=complex)
                    for c in cycles:
                        a_idx = c[0]
                        b_idx = g[a_idx]
                        c_idx = g[b_idx]
                        x[a_idx] = 1.0
                        x[b_idx] = omega
                        x[c_idx] = omega**2
                    
                    # Evaluate the polynomial
                    total = 0.0
                    for k, orbit in enumerate(orbits):
                        orbit_sum = 0.0
                        for m in orbit:
                            term = coeffs[k]
                            for i in range(6):
                                term *= x[i] ** m[i]
                            orbit_sum += term
                        total += orbit_sum
                    
                    if abs(total) > 1e-10:
                        n_nonzero += 1
                
                print(f"  Numerical test: {n_nonzero}/{n_trials} random polynomials nonzero at fixed point")
                
                if n_nonzero == n_trials:
                    print(f"  {PASS}: Generic invariant polynomial is nonzero at fixed point!")
                elif n_nonzero > n_trials * 0.9:
                    print(f"  {PASS}: Almost always nonzero ({n_nonzero}/{n_trials})")
                elif n_nonzero == 0:
                    print(f"  {FAIL}: Polynomial ALWAYS vanishes at fixed point!")
                    print(f"  This means the orbit sums are secretly zero here!")
                else:
                    print(f"  {WARN}: Nonzero {n_nonzero}/{n_trials} times — suspicious")
    
    # =========================================================
    # TEST 3: ALSO NUMERICALLY TEST PURE g1, g2 FIXED CURVES
    # =========================================================
    section("3. Numerical Verification of Fixed Curves (pure g1, g2)")
    
    # For pure g2 = (1,2,3), the fixed curve is parameterized by:
    # x_0 free, x_1 = t, x_2 = omega*t, x_3 = omega^2*t, x_4 free, x_5 free
    # We sample random points on this curve and check if the polynomial vanishes.
    
    omega = np.exp(2j * np.pi / 3)
    
    # Random invariant polynomial
    # Compute orbits
    full_group = []
    curr = identity[:]
    for i in range(3):
        temp = curr[:]
        for j in range(3):
            full_group.append(temp[:])
            temp = compose_perm(g2, temp)
        curr = compose_perm(g1, curr)
    
    orbits = []
    visited_m = set()
    for m in monomials:
        if m not in visited_m:
            orbit = set()
            for grp in full_group:
                orbit.add(apply_perm_to_monomial(m, grp))
            orbits.append(orbit)
            visited_m.update(orbit)
    
    print(f"\nTesting pure g2 = (1,2,3) fixed locus:")
    print(f"  Fixed locus: x_2 = ω*x_1, x_3 = ω²*x_1, others free")
    
    # The invariant polynomial restricted to Fix(g2) is a polynomial in (x_0, x_1, x_4, x_5)
    # We already know 16 monomials survive. Let's evaluate at random points.
    
    np.random.seed(123)
    coeffs = np.random.randn(len(orbits)) + 1j * np.random.randn(len(orbits))
    
    n_points = 20
    n_zero = 0
    for _ in range(n_points):
        x = np.random.randn(6) + 1j * np.random.randn(6)
        # Fix the g2-constraint
        x[2] = omega * x[1]
        x[3] = omega**2 * x[1]
        
        total = 0.0
        for k, orbit in enumerate(orbits):
            for m in orbit:
                term = coeffs[k]
                for i in range(6):
                    if m[i] != 0:
                        term *= x[i] ** m[i]
                total += term
        
        if abs(total) < 1e-6:
            n_zero += 1
    
    print(f"  Random points on Fix(g2): {n_zero}/{n_points} zeros found")
    if n_zero == 0:
        print(f"  The polynomial is generically NONZERO on Fix(g2)")
        print(f"  But the CY is defined by P=0, so Fix(g2) ∩ CY is the ZERO SET of P|_Fix")
        print(f"  A nonzero polynomial of degree 3 on P2 has a CURVE of zeros")
        print(f"  => Fixed CURVE on CY (as expected)")
    
    # Let's find actual zeros using a simple search
    print(f"  Searching for zeros of P|_Fix(g2) (= fixed points on CY)...")
    from scipy.optimize import minimize
    
    def objective(params):
        # params = [re(x0), im(x0), re(x1), im(x1), re(x4), im(x4), re(x5), im(x5)]
        x = np.zeros(6, dtype=complex)
        x[0] = params[0] + 1j * params[1]
        x[1] = params[2] + 1j * params[3]
        x[2] = omega * x[1]
        x[3] = omega**2 * x[1]
        x[4] = params[4] + 1j * params[5]
        x[5] = params[6] + 1j * params[7]
        
        total = 0.0 + 0j
        for k, orbit in enumerate(orbits):
            for m in orbit:
                term = coeffs[k]
                for i in range(6):
                    if m[i] != 0:
                        term *= x[i] ** m[i]
                total += term
        
        return abs(total)**2
    
    best_val = float('inf')
    for trial in range(50):
        x0 = np.random.randn(8) * 0.5
        result = minimize(objective, x0, method='Nelder-Mead', 
                         options={'maxiter': 10000, 'xatol': 1e-12, 'fatol': 1e-20})
        if result.fun < best_val:
            best_val = result.fun
    
    print(f"  Best |P|² found: {best_val:.2e}")
    if best_val < 1e-15:
        print(f"  {FAIL}: Found a zero! (confirming fixed points on CY)")
    elif best_val < 1e-6:
        print(f"  {WARN}: Near-zero found — likely a fixed point")
    else:
        print(f"  Hmm, didn't find a zero numerically (optimizer may have failed)")
    
    # =========================================================
    # TEST 4: WHAT CAN WE SALVAGE?
    # =========================================================
    section("4. Salvage Analysis")
    
    print(f"\nOriginal manifold: h11={h11_val}, h21={h21_val}, chi={chi}")
    print(f"Full Z_3 x Z_3 quotient: SINGULAR (fixed curves from pure g1, g2)")
    
    print(f"\nDiagonal Z_3 subgroups (act freely!):")
    print(f"  <g1∘g2>:  chi = {chi}/3 = {chi//3} => |chi|/2 = {abs(chi//3)//2} generations")
    print(f"  <g1∘g2²>: chi = {chi}/3 = {chi//3} => |chi|/2 = {abs(chi//3)//2} generations")
    
    # For the diagonal Z_3 quotient, compute Hodge numbers via Lefschetz
    # h11(X/G) = number of G-invariant (1,1) forms
    # h21(X/G) = number of G-invariant (2,1) forms
    # For Z_3 acting freely: chi(X/G) = chi(X)/3 = -18
    # h11(X/G) - h21(X/G) = chi(X/G)/2 = -9
    # Also h11(X/G) + h21(X/G) = dim H^2 + dim H^3... 
    # Actually for a free Z_3 quotient:
    # h11(X/G) = h11_inv where h11_inv counts G-invariant divisors
    # h21(X/G) = (chi(X/G) - 2 + 2*h11(X/G)) / (-2) ... no
    # chi = 2(h11 - h21) => h21 - h11 = -chi/2 = 9
    # We need another relation. Typically:
    # h11(X/G) = number of toric divisors that are G-invariant
    
    print(f"\n  For the diagonal Z_3 quotient:")
    print(f"  h21 - h11 = |chi|/2 = {abs(chi//3)//2}")
    
    # The toric divisors correspond to the rays (vertices).
    # Under the diagonal Z_3 <g1∘g2>, the orbits of rays are:
    # g1∘g2 = {diag1_gen}
    print(f"\n  Ray orbits under <g1∘g2> = {diag1_gen}:")
    visited_r = [False] * 6
    ray_orbits = []
    for i in range(6):
        if not visited_r[i]:
            orb = []
            j = i
            while not visited_r[j]:
                visited_r[j] = True
                orb.append(j)
                j = diag1_gen[j]
            ray_orbits.append(orb)
    for orb in ray_orbits:
        print(f"    {orb}")
    n_inv_divisors = len(ray_orbits)
    print(f"  Number of invariant toric divisors: {n_inv_divisors}")
    print(f"  But h11(X) = {h11_val} (not all toric divs are independent)")
    print(f"  For a free quotient: h11(X/G) <= h11(X)")
    print(f"  If action permutes the two independent divisor classes: h11(X/G) = 1")
    print(f"  If action fixes both classes: h11(X/G) = 2")
    
    # Check: what does g1∘g2 do to the two weight vectors?
    # Weights: w1 = [0,1,1,1,0,0], w2 = [1,0,0,0,1,1]
    # Under g1∘g2 = [4,2,3,1,5,0]:
    #   w1' = [w1[4], w1[2], w1[3], w1[1], w1[5], w1[0]] = [0,1,1,1,0,0] = w1
    #   w2' = [w2[4], w2[2], w2[3], w2[1], w2[5], w2[0]] = [1,0,0,0,1,1] = w2
    w1 = np.array([0,1,1,1,0,0])
    w2 = np.array([1,0,0,0,1,1])
    w1_perm = np.array([w1[diag1_gen[i]] for i in range(6)])
    w2_perm = np.array([w2[diag1_gen[i]] for i in range(6)])
    
    print(f"\n  Weight w1 under g1∘g2: {w1} -> {w1_perm} {'(invariant)' if np.all(w1==w1_perm) else '(NOT invariant)'}")
    print(f"  Weight w2 under g1∘g2: {w2} -> {w2_perm} {'(invariant)' if np.all(w2==w2_perm) else '(NOT invariant)'}")
    
    if np.all(w1 == w1_perm) and np.all(w2 == w2_perm):
        # Both divisor classes are invariant
        h11_quotient = h11_val
        h21_quotient = h21_val // 3 + (h21_val % 3)  # rough estimate
        # Actually: h21 - h11 = 9, and h11 = 2 => h21 = 11
        h21_quotient = h11_quotient + abs(chi // 3) // 2
        chi_quotient = 2 * (h11_quotient - h21_quotient)
        print(f"\n  Both divisor classes invariant => h11(X/G) = {h11_quotient}")
        print(f"  h21(X/G) = h11 + |chi/3|/2 = {h11_quotient} + {abs(chi//3)//2} = {h21_quotient}")
        print(f"  chi(X/G) = 2*({h11_quotient} - {h21_quotient}) = {chi_quotient}")
    
    # =========================================================
    # TEST 5: ORBIFOLD RESOLUTION CHECK
    # =========================================================
    section("5. Orbifold Resolution for Full Z_3 x Z_3")
    
    print(f"If we take the FULL Z_3 x Z_3 quotient despite the singularities:")
    print(f"  The quotient is an ORBIFOLD (mild singularities)")
    print(f"  The singular locus has contributions from:")
    print(f"    - Fixed curves of pure g1 (3-cycle on vertices 0,4,5)")
    print(f"    - Fixed curves of pure g2 (3-cycle on vertices 1,2,3)")
    print(f"    - Fixed curves of pure g1², g2² (same loci)")
    print(f"")
    print(f"  Resolution of a Z_3 orbifold singularity along a curve:")
    print(f"    - Each curve contributes +2 to h11 in the resolution")
    print(f"    - (local model: C²/Z_3 has one exceptional divisor)")
    print(f"")
    
    # Count the number of distinct fixed curves
    # Under g2 = (1,2,3): Fix(g2) ∩ CY is a curve on the 2D projective space
    #   parameterized by (x_0, x_4, x_5) with degree 3 in these coords.
    #   This is a genus-1 curve (cubic in P2).
    # Under g2^2 = (1,3,2): same fixed locus (just different omega)!
    #   Actually g2 and g2^2 have the SAME fixed locus! (same cycle, different eigenvalue)
    # Under g1 = (0,4,5): Fix(g1) ∩ CY is a curve in (x_1, x_2, x_3) coords.
    # Under g1^2 = (0,5,4): same fixed locus as g1.
    
    print(f"  Distinct fixed curves:")
    print(f"    Curve 1: from g2, g2² (cycle 1,2,3) - cubic in P2 (genus 1)")
    print(f"    Curve 2: from g1, g1² (cycle 0,4,5) - cubic in P2 (genus 1)")
    print(f"  Total: 2 distinct fixed curves")
    print(f"")
    
    # Under the Z_3 x Z_3 action, these curves might be identified
    # g1 acts on Curve 1 (the g2-fixed curve) — does it map it to itself?
    # Curve 1 is at x_2=omega*x_1, x_3=omega^2*x_1, parameterized by (x_0,x_1,x_4,x_5)
    # g1 maps x_0->x_4, x_4->x_5, x_5->x_0, x_1->x_1, x_2->x_2, x_3->x_3
    # So g1 permutes (x_0,x_4,x_5) cyclically but keeps (x_1,x_2,x_3) fixed
    # This means g1 DOES map Curve 1 to itself (it acts on the curve!)
    # Similarly, g2 acts on Curve 2.
    
    print(f"  Under the Z_3 x Z_3 quotient:")
    print(f"    g1 acts on Curve 1 (the g2-fixed curve) by permuting (x_0,x_4,x_5)")
    print(f"    g2 acts on Curve 2 (the g1-fixed curve) by permuting (x_1,x_2,x_3)")
    print(f"    Each curve maps to a single singular point in the quotient")
    print(f"")
    print(f"  After resolution, the orbifold Euler characteristic changes:")
    print(f"    chi(orbifold) = chi(CY)/|G| = {chi}/9 = {chi//9}")
    print(f"    Resolution adds: each Z_3 curve singularity contributes to chi")
    print(f"    The resolved chi depends on the topology of the fixed curves")
    
    # =========================================================
    # FINAL VERDICT
    # =========================================================
    section("FINAL VERDICT")
    
    print(f"""
DRAGON STATUS: Partial Dragon — Partially Real, Partially False

WHAT'S REAL:
  ✓ The polytope (h11=2, h21=29, chi=-54) exists and is correct
  ✓ The Z_3 x Z_3 symmetry is GENUINE (lattice automorphisms, det=1)  
  ✓ The monomials transform correctly under the group
  ✓ The orbits are correct and there exist invariant polynomials
  ✓ Combined elements (g1*g2, g1*g2², g1²*g2, g1²*g2²) act FREELY

WHAT'S FALSE:
  ✗ Pure g1 and g2 have FIXED CURVES on the CY hypersurface
  ✗ The full Z_3 x Z_3 quotient is SINGULAR (orbifold)
  ✗ chi = -6 with 3 generations is NOT directly achieved
  ✗ The polytope is NOT P2 x P2 (that was a misidentification)

WHAT'S SALVAGEABLE:
  → Diagonal Z_3 quotient (by <g1*g2>) acts FREELY
    chi = -54/3 = -18, giving |chi|/2 = 9 generations
    Not 3 generations, but still a valid smooth quotient
  
  → The orbifold Z_3 x Z_3 quotient might be resolvable
    If the resolution preserves chi = -6, we still get 3 generations
    But this requires careful analysis of the exceptional divisors
    (and typically chi CHANGES under resolution)

CONFIDENCE: The freely-acting claim for the FULL Z_3 x Z_3 is FALSE.
The diagonal Z_3 quotient is the honest result.
""")

if __name__ == "__main__":
    main()
